### ISSUE TITLE
getline not standard C yet!

### ISSUE THREAD

**Issue by keith-skinner** [arewhyaeenn/CI_LISP#10]
https://github.com/arewhyaeenn/CI_LISP/blob/5341511fedc42a6463c4ecec5406440824a205d4/src/ciLisp.l#L65

an implementation from W3
https://dev.w3.org/libwww/Library/src/vms/getline.c

**Comment by arewhyaeenn** [comment]
Thanks Keith. getline implementation (modified to include extra terminators) added.
